// Auto-generated. Do not edit!

// (in-package flexbe_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class BehaviorExecutionGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.behavior_name = null;
      this.arg_keys = null;
      this.arg_values = null;
      this.input_keys = null;
      this.input_values = null;
    }
    else {
      if (initObj.hasOwnProperty('behavior_name')) {
        this.behavior_name = initObj.behavior_name
      }
      else {
        this.behavior_name = '';
      }
      if (initObj.hasOwnProperty('arg_keys')) {
        this.arg_keys = initObj.arg_keys
      }
      else {
        this.arg_keys = [];
      }
      if (initObj.hasOwnProperty('arg_values')) {
        this.arg_values = initObj.arg_values
      }
      else {
        this.arg_values = [];
      }
      if (initObj.hasOwnProperty('input_keys')) {
        this.input_keys = initObj.input_keys
      }
      else {
        this.input_keys = [];
      }
      if (initObj.hasOwnProperty('input_values')) {
        this.input_values = initObj.input_values
      }
      else {
        this.input_values = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type BehaviorExecutionGoal
    // Serialize message field [behavior_name]
    bufferOffset = _serializer.string(obj.behavior_name, buffer, bufferOffset);
    // Serialize message field [arg_keys]
    bufferOffset = _arraySerializer.string(obj.arg_keys, buffer, bufferOffset, null);
    // Serialize message field [arg_values]
    bufferOffset = _arraySerializer.string(obj.arg_values, buffer, bufferOffset, null);
    // Serialize message field [input_keys]
    bufferOffset = _arraySerializer.string(obj.input_keys, buffer, bufferOffset, null);
    // Serialize message field [input_values]
    bufferOffset = _arraySerializer.string(obj.input_values, buffer, bufferOffset, null);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type BehaviorExecutionGoal
    let len;
    let data = new BehaviorExecutionGoal(null);
    // Deserialize message field [behavior_name]
    data.behavior_name = _deserializer.string(buffer, bufferOffset);
    // Deserialize message field [arg_keys]
    data.arg_keys = _arrayDeserializer.string(buffer, bufferOffset, null)
    // Deserialize message field [arg_values]
    data.arg_values = _arrayDeserializer.string(buffer, bufferOffset, null)
    // Deserialize message field [input_keys]
    data.input_keys = _arrayDeserializer.string(buffer, bufferOffset, null)
    // Deserialize message field [input_values]
    data.input_values = _arrayDeserializer.string(buffer, bufferOffset, null)
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.behavior_name.length;
    object.arg_keys.forEach((val) => {
      length += 4 + val.length;
    });
    object.arg_values.forEach((val) => {
      length += 4 + val.length;
    });
    object.input_keys.forEach((val) => {
      length += 4 + val.length;
    });
    object.input_values.forEach((val) => {
      length += 4 + val.length;
    });
    return length + 20;
  }

  static datatype() {
    // Returns string type for a message object
    return 'flexbe_msgs/BehaviorExecutionGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '448c2298fe3c13b6fd73cfc07e865a14';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Commands the execution of any behavior.
    
    # name of the behavior to be executed
    string behavior_name
    
    # optional list of behavior parameters
    string[] arg_keys
    string[] arg_values
    
    # optional list of initial userdata
    string[] input_keys
    string[] input_values
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new BehaviorExecutionGoal(null);
    if (msg.behavior_name !== undefined) {
      resolved.behavior_name = msg.behavior_name;
    }
    else {
      resolved.behavior_name = ''
    }

    if (msg.arg_keys !== undefined) {
      resolved.arg_keys = msg.arg_keys;
    }
    else {
      resolved.arg_keys = []
    }

    if (msg.arg_values !== undefined) {
      resolved.arg_values = msg.arg_values;
    }
    else {
      resolved.arg_values = []
    }

    if (msg.input_keys !== undefined) {
      resolved.input_keys = msg.input_keys;
    }
    else {
      resolved.input_keys = []
    }

    if (msg.input_values !== undefined) {
      resolved.input_values = msg.input_values;
    }
    else {
      resolved.input_values = []
    }

    return resolved;
    }
};

module.exports = BehaviorExecutionGoal;
