// Generated by gencpp from file flexbe_msgs/BehaviorSynthesisActionGoal.msg
// DO NOT EDIT!


#ifndef FLEXBE_MSGS_MESSAGE_BEHAVIORSYNTHESISACTIONGOAL_H
#define FLEXBE_MSGS_MESSAGE_BEHAVIORSYNTHESISACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <flexbe_msgs/BehaviorSynthesisGoal.h>

namespace flexbe_msgs
{
template <class ContainerAllocator>
struct BehaviorSynthesisActionGoal_
{
  typedef BehaviorSynthesisActionGoal_<ContainerAllocator> Type;

  BehaviorSynthesisActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  BehaviorSynthesisActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::flexbe_msgs::BehaviorSynthesisGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::flexbe_msgs::BehaviorSynthesisActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flexbe_msgs::BehaviorSynthesisActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct BehaviorSynthesisActionGoal_

typedef ::flexbe_msgs::BehaviorSynthesisActionGoal_<std::allocator<void> > BehaviorSynthesisActionGoal;

typedef boost::shared_ptr< ::flexbe_msgs::BehaviorSynthesisActionGoal > BehaviorSynthesisActionGoalPtr;
typedef boost::shared_ptr< ::flexbe_msgs::BehaviorSynthesisActionGoal const> BehaviorSynthesisActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::flexbe_msgs::BehaviorSynthesisActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::flexbe_msgs::BehaviorSynthesisActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::flexbe_msgs::BehaviorSynthesisActionGoal_<ContainerAllocator1> & lhs, const ::flexbe_msgs::BehaviorSynthesisActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::flexbe_msgs::BehaviorSynthesisActionGoal_<ContainerAllocator1> & lhs, const ::flexbe_msgs::BehaviorSynthesisActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace flexbe_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::flexbe_msgs::BehaviorSynthesisActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flexbe_msgs::BehaviorSynthesisActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flexbe_msgs::BehaviorSynthesisActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flexbe_msgs::BehaviorSynthesisActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flexbe_msgs::BehaviorSynthesisActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flexbe_msgs::BehaviorSynthesisActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::flexbe_msgs::BehaviorSynthesisActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef3bccd0f7dc68c4fe76a2cb791126b0";
  }

  static const char* value(const ::flexbe_msgs::BehaviorSynthesisActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef3bccd0f7dc68c4ULL;
  static const uint64_t static_value2 = 0xfe76a2cb791126b0ULL;
};

template<class ContainerAllocator>
struct DataType< ::flexbe_msgs::BehaviorSynthesisActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "flexbe_msgs/BehaviorSynthesisActionGoal";
  }

  static const char* value(const ::flexbe_msgs::BehaviorSynthesisActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::flexbe_msgs::BehaviorSynthesisActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"BehaviorSynthesisGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: flexbe_msgs/BehaviorSynthesisGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Minimal template for a behavior synthesis action.\n"
"# As long as your action type supports at least the fields listed below, you can also use a custom one.\n"
"\n"
"# Request message as set in the FlexBE UI\n"
"SynthesisRequest request\n"
"\n"
"\n"
"================================================================================\n"
"MSG: flexbe_msgs/SynthesisRequest\n"
"# Minimal template for the request data provided by the FlexBE synthesis interface.\n"
"# Either refer this message as 'request' in the goal part of your synthesis action\n"
"# or implement your own by at least supporting the fields listed below.\n"
"\n"
"# Identifier of this synthesis query, can for example be used to set the name of the resulting state machine\n"
"string name\n"
"\n"
"# Identifier of the system (i.e., configuration data set) to be used by the synthesis tool\n"
"string system\n"
"\n"
"# Goal to be achieved by the synthesized behavior\n"
"string goal\n"
"\n"
"# Initial conditions from which the synthesized behavior will start\n"
"string initial_condition\n"
"\n"
"# Available outcomes of the generated state machine,\n"
"# i.e., possible results of the synthesized behavior\n"
"string[] sm_outcomes\n"
;
  }

  static const char* value(const ::flexbe_msgs::BehaviorSynthesisActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::flexbe_msgs::BehaviorSynthesisActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BehaviorSynthesisActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flexbe_msgs::BehaviorSynthesisActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::flexbe_msgs::BehaviorSynthesisActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::flexbe_msgs::BehaviorSynthesisGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLEXBE_MSGS_MESSAGE_BEHAVIORSYNTHESISACTIONGOAL_H
