// Generated by gencpp from file flexbe_msgs/ContainerStructure.msg
// DO NOT EDIT!


#ifndef FLEXBE_MSGS_MESSAGE_CONTAINERSTRUCTURE_H
#define FLEXBE_MSGS_MESSAGE_CONTAINERSTRUCTURE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <flexbe_msgs/Container.h>

namespace flexbe_msgs
{
template <class ContainerAllocator>
struct ContainerStructure_
{
  typedef ContainerStructure_<ContainerAllocator> Type;

  ContainerStructure_()
    : behavior_id(0)
    , containers()  {
    }
  ContainerStructure_(const ContainerAllocator& _alloc)
    : behavior_id(0)
    , containers(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _behavior_id_type;
  _behavior_id_type behavior_id;

   typedef std::vector< ::flexbe_msgs::Container_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::flexbe_msgs::Container_<ContainerAllocator> >::other >  _containers_type;
  _containers_type containers;





  typedef boost::shared_ptr< ::flexbe_msgs::ContainerStructure_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flexbe_msgs::ContainerStructure_<ContainerAllocator> const> ConstPtr;

}; // struct ContainerStructure_

typedef ::flexbe_msgs::ContainerStructure_<std::allocator<void> > ContainerStructure;

typedef boost::shared_ptr< ::flexbe_msgs::ContainerStructure > ContainerStructurePtr;
typedef boost::shared_ptr< ::flexbe_msgs::ContainerStructure const> ContainerStructureConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::flexbe_msgs::ContainerStructure_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::flexbe_msgs::ContainerStructure_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::flexbe_msgs::ContainerStructure_<ContainerAllocator1> & lhs, const ::flexbe_msgs::ContainerStructure_<ContainerAllocator2> & rhs)
{
  return lhs.behavior_id == rhs.behavior_id &&
    lhs.containers == rhs.containers;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::flexbe_msgs::ContainerStructure_<ContainerAllocator1> & lhs, const ::flexbe_msgs::ContainerStructure_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace flexbe_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::flexbe_msgs::ContainerStructure_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flexbe_msgs::ContainerStructure_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flexbe_msgs::ContainerStructure_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flexbe_msgs::ContainerStructure_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flexbe_msgs::ContainerStructure_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flexbe_msgs::ContainerStructure_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::flexbe_msgs::ContainerStructure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9cd26d15621063b90279d87117694328";
  }

  static const char* value(const ::flexbe_msgs::ContainerStructure_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9cd26d15621063b9ULL;
  static const uint64_t static_value2 = 0x0279d87117694328ULL;
};

template<class ContainerAllocator>
struct DataType< ::flexbe_msgs::ContainerStructure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "flexbe_msgs/ContainerStructure";
  }

  static const char* value(const ::flexbe_msgs::ContainerStructure_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::flexbe_msgs::ContainerStructure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 behavior_id\n"
"Container[] containers\n"
"================================================================================\n"
"MSG: flexbe_msgs/Container\n"
"string path\n"
"string[] children\n"
"string[] outcomes\n"
"string[] transitions\n"
"byte[] autonomy\n"
;
  }

  static const char* value(const ::flexbe_msgs::ContainerStructure_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::flexbe_msgs::ContainerStructure_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.behavior_id);
      stream.next(m.containers);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ContainerStructure_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flexbe_msgs::ContainerStructure_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::flexbe_msgs::ContainerStructure_<ContainerAllocator>& v)
  {
    s << indent << "behavior_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.behavior_id);
    s << indent << "containers[]" << std::endl;
    for (size_t i = 0; i < v.containers.size(); ++i)
    {
      s << indent << "  containers[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::flexbe_msgs::Container_<ContainerAllocator> >::stream(s, indent + "    ", v.containers[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLEXBE_MSGS_MESSAGE_CONTAINERSTRUCTURE_H
