// Generated by gencpp from file final_project/Centroid.msg
// DO NOT EDIT!


#ifndef FINAL_PROJECT_MESSAGE_CENTROID_H
#define FINAL_PROJECT_MESSAGE_CENTROID_H

#include <ros/service_traits.h>


#include <final_project/CentroidRequest.h>
#include <final_project/CentroidResponse.h>


namespace final_project
{

struct Centroid
{

typedef CentroidRequest Request;
typedef CentroidResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Centroid
} // namespace final_project


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::final_project::Centroid > {
  static const char* value()
  {
    return "e312be5ce6c21441e8388059848bcd52";
  }

  static const char* value(const ::final_project::Centroid&) { return value(); }
};

template<>
struct DataType< ::final_project::Centroid > {
  static const char* value()
  {
    return "final_project/Centroid";
  }

  static const char* value(const ::final_project::Centroid&) { return value(); }
};


// service_traits::MD5Sum< ::final_project::CentroidRequest> should match
// service_traits::MD5Sum< ::final_project::Centroid >
template<>
struct MD5Sum< ::final_project::CentroidRequest>
{
  static const char* value()
  {
    return MD5Sum< ::final_project::Centroid >::value();
  }
  static const char* value(const ::final_project::CentroidRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::final_project::CentroidRequest> should match
// service_traits::DataType< ::final_project::Centroid >
template<>
struct DataType< ::final_project::CentroidRequest>
{
  static const char* value()
  {
    return DataType< ::final_project::Centroid >::value();
  }
  static const char* value(const ::final_project::CentroidRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::final_project::CentroidResponse> should match
// service_traits::MD5Sum< ::final_project::Centroid >
template<>
struct MD5Sum< ::final_project::CentroidResponse>
{
  static const char* value()
  {
    return MD5Sum< ::final_project::Centroid >::value();
  }
  static const char* value(const ::final_project::CentroidResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::final_project::CentroidResponse> should match
// service_traits::DataType< ::final_project::Centroid >
template<>
struct DataType< ::final_project::CentroidResponse>
{
  static const char* value()
  {
    return DataType< ::final_project::Centroid >::value();
  }
  static const char* value(const ::final_project::CentroidResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FINAL_PROJECT_MESSAGE_CENTROID_H
