// Generated by gencpp from file my_gazebo/ConveyorBeltControl.msg
// DO NOT EDIT!


#ifndef MY_GAZEBO_MESSAGE_CONVEYORBELTCONTROL_H
#define MY_GAZEBO_MESSAGE_CONVEYORBELTCONTROL_H

#include <ros/service_traits.h>


#include <my_gazebo/ConveyorBeltControlRequest.h>
#include <my_gazebo/ConveyorBeltControlResponse.h>


namespace my_gazebo
{

struct ConveyorBeltControl
{

typedef ConveyorBeltControlRequest Request;
typedef ConveyorBeltControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ConveyorBeltControl
} // namespace my_gazebo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_gazebo::ConveyorBeltControl > {
  static const char* value()
  {
    return "9530768849645096e15ae7f875771ab2";
  }

  static const char* value(const ::my_gazebo::ConveyorBeltControl&) { return value(); }
};

template<>
struct DataType< ::my_gazebo::ConveyorBeltControl > {
  static const char* value()
  {
    return "my_gazebo/ConveyorBeltControl";
  }

  static const char* value(const ::my_gazebo::ConveyorBeltControl&) { return value(); }
};


// service_traits::MD5Sum< ::my_gazebo::ConveyorBeltControlRequest> should match
// service_traits::MD5Sum< ::my_gazebo::ConveyorBeltControl >
template<>
struct MD5Sum< ::my_gazebo::ConveyorBeltControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_gazebo::ConveyorBeltControl >::value();
  }
  static const char* value(const ::my_gazebo::ConveyorBeltControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_gazebo::ConveyorBeltControlRequest> should match
// service_traits::DataType< ::my_gazebo::ConveyorBeltControl >
template<>
struct DataType< ::my_gazebo::ConveyorBeltControlRequest>
{
  static const char* value()
  {
    return DataType< ::my_gazebo::ConveyorBeltControl >::value();
  }
  static const char* value(const ::my_gazebo::ConveyorBeltControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_gazebo::ConveyorBeltControlResponse> should match
// service_traits::MD5Sum< ::my_gazebo::ConveyorBeltControl >
template<>
struct MD5Sum< ::my_gazebo::ConveyorBeltControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_gazebo::ConveyorBeltControl >::value();
  }
  static const char* value(const ::my_gazebo::ConveyorBeltControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_gazebo::ConveyorBeltControlResponse> should match
// service_traits::DataType< ::my_gazebo::ConveyorBeltControl >
template<>
struct DataType< ::my_gazebo::ConveyorBeltControlResponse>
{
  static const char* value()
  {
    return DataType< ::my_gazebo::ConveyorBeltControl >::value();
  }
  static const char* value(const ::my_gazebo::ConveyorBeltControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_GAZEBO_MESSAGE_CONVEYORBELTCONTROL_H
