robot1:
  kinematics_solver: cached_ik_kinematics_plugin/CachedSrvKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
robot2:
  kinematics_solver: cached_ik_kinematics_plugin/CachedSrvKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005